% -------------------------------------------------------------------
%  Generated by MATLAB on 21-Nov-2014 17:14:05
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------

% This m-file generates the REF-Matrix (ref.mat) for a faster research

saveVarsMat = load('ref.mat');

REF = saveVarsMat.REF; % <101x101 double> too many elements

clear saveVarsMat;
